<?php

namespace App\Filament\Resources\AirCargoBookings\Schemas;

use App\Models\AirCargoModel;
use Filament\Infolists\Components\ImageEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Components\Html;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Illuminate\Support\Facades\File;
use Illuminate\Support\HtmlString;

class AirCargoBookingInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make('Booking')
                    ->schema([
                        TextEntry::make('shipping_id')->label('Reference')->copyable(),
                        TextEntry::make('transaction_id')->label('Transaction ID')->copyable()->placeholder('-'),
                        TextEntry::make('transaction_ref')->label('Transaction ref')->copyable()->placeholder('-'),
                        TextEntry::make('payment_status')->badge()->color(fn (string $state): string => match ($state) {
                            'successful' => 'success',
                            'failed', 'cancelled' => 'danger',
                            default => 'warning',
                        }),
                        TextEntry::make('created_at')->label('Booked')->dateTime(),
                    ])
                    ->columns(3),

                Section::make('Customer')
                    ->schema([
                        TextEntry::make('fullname')->label('Name'),
                        TextEntry::make('email')->copyable(),
                        TextEntry::make('phone')->label('Phone')->copyable(),
                    ])
                    ->columns(3),

                Section::make('Shipment')
                    ->schema([
                        TextEntry::make('shipment_type')->label('Type')->badge(),
                        TextEntry::make('shipping_to')->label('Destination'),
                        TextEntry::make('price')->label('Unit price'),
                        TextEntry::make('total_price')->label('Total'),
                    ])
                    ->columns(4),

                Section::make('Uploaded Preview Document')
                    ->description('Image (.jpg/.png) or PDF the customer uploaded of the shipment.')
                    ->schema([
                        ImageEntry::make('shipment_preview_image')
                            ->hiddenLabel()
                            ->getStateUsing(fn (AirCargoModel $record): ?string => asset('assets/aircargo/' . $record->shipment_preview))
                            ->visible(fn (AirCargoModel $record): bool => self::previewMimeType($record) !== null && str_starts_with(self::previewMimeType($record), 'image/'))
                            ->height(300),
                        Html::make(fn (AirCargoModel $record): HtmlString => new HtmlString(
                            '<iframe src="' . e(asset('assets/aircargo/' . $record->shipment_preview)) . '" style="width:100%;height:600px;border:1px solid #e5e7eb;border-radius:8px;"></iframe>'
                        ))
                            ->visible(fn (AirCargoModel $record): bool => self::previewMimeType($record) === 'application/pdf')
                            ->columnSpanFull(),
                        TextEntry::make('no_preview')
                            ->hiddenLabel()
                            ->state('No preview document was uploaded for this shipment.')
                            ->visible(fn (AirCargoModel $record): bool => blank($record->shipment_preview)),
                        TextEntry::make('unreadable_preview')
                            ->hiddenLabel()
                            ->state('Preview file is recorded but missing or unreadable on the server.')
                            ->visible(fn (AirCargoModel $record): bool => filled($record->shipment_preview) && self::previewMimeType($record) === null),
                    ]),

                Section::make('Generated Shipment Document')
                    ->description('Label/manifest PDF generated by the system and emailed to the customer.')
                    ->schema([
                        Html::make(fn (AirCargoModel $record): HtmlString => new HtmlString(
                            '<iframe src="' . e(route('admin.aircargo.document.preview', $record)) . '" style="width:100%;height:600px;border:1px solid #e5e7eb;border-radius:8px;"></iframe>'
                        ))
                            ->visible(fn (AirCargoModel $record): bool => filled($record->shipment_details))
                            ->columnSpanFull(),
                        TextEntry::make('no_document')
                            ->hiddenLabel()
                            ->state('No shipment document has been generated for this booking.')
                            ->visible(fn (AirCargoModel $record): bool => blank($record->shipment_details)),
                    ]),
            ]);
    }

    private static function previewMimeType(AirCargoModel $record): ?string
    {
        if (blank($record->shipment_preview)) {
            return null;
        }

        $path = public_path('assets/aircargo/' . $record->shipment_preview);

        return File::exists($path) ? File::mimeType($path) : null;
    }
}
