<div class="va-page" x-data x-on:visa-step-changed.window="window.scrollTo({top: 0, behavior: 'smooth'})">
    <link rel="stylesheet" href="{{ asset('css/visa-application.css') }}">
    @php
        $steps = ['Trip details','Travelers','Passports','Questions','Services','Documents','Review','Payment'];
        $product = $application->product;
    @endphp

    <header class="va-header">
        <a href="{{ route('visa.results') }}" class="va-back"><x-ui.icon name="arrow-left" :size="17" /> Visa results</a>
        <div><span>Application {{ $application->reference }}</span><strong>{{ $product->name }}</strong></div>
        <small class="va-saved" wire:loading.class="is-saving"><x-ui.icon name="cloud-check" :size="18" /> <span wire:loading.remove>{{ $savedMessage ?: 'Draft saved securely' }}</span><span wire:loading>Saving…</span></small>
    </header>

    <nav class="va-stepper" aria-label="Application progress">
        @foreach($steps as $index => $label)
            @php $number=$index+1; $accessible=$number <= min(8,$application->completed_step+1); @endphp
            <button type="button" wire:click="goTo({{ $number }})" @disabled(!$accessible) class="{{ $step===$number?'is-current':'' }} {{ $number <= $application->completed_step?'is-complete':'' }}">
                <b>{{ $number <= $application->completed_step ? '✓' : $number }}</b><span>{{ $label }}</span>
            </button>
        @endforeach
    </nav>

    <div class="va-layout">
        <main class="va-card">
            @if($errors->any())
                <div class="va-validation-summary" role="alert" aria-live="assertive">
                    <x-ui.icon name="alert-circle" :size="20" />
                    <div><strong>Please check the highlighted fields.</strong><span>{{ $errors->first() }}</span></div>
                </div>
            @endif
            @if($step === 1)
                <div class="va-title"><span>Step 1 of 8</span><h1>Confirm your trip</h1><p>We brought these details forward from your visa search.</p></div>
                <div class="va-summary"><div><small>Route</small><strong>{{ data_get($application->search_snapshot,'nationality_name') }} → {{ data_get($application->search_snapshot,'destination_name') }}</strong></div><div><small>Travel dates</small><strong>{{ $application->arrival_date->format('d M Y') }} – {{ $application->departure_date->format('d M Y') }}</strong></div><div><small>Travelers</small><strong>{{ $application->travelers->count() }}</strong></div></div>
                <div class="va-grid va-grid--2">
                    <label @class(['is-invalid' => $errors->has('contactEmail')])><span>Contact email *</span><input type="email" wire:model.live.debounce.500ms="contactEmail" autocomplete="email" @class(['is-invalid' => $errors->has('contactEmail')]) aria-invalid="{{ $errors->has('contactEmail') ? 'true' : 'false' }}">@error('contactEmail')<em role="alert">{{ $message }}</em>@enderror</label>
                    <label @class(['is-invalid' => $errors->has('processingOptionId')])><span>Processing option *</span><select wire:model.live="processingOptionId" @class(['is-invalid' => $errors->has('processingOptionId')]) aria-invalid="{{ $errors->has('processingOptionId') ? 'true' : 'false' }}"><option value="">Choose processing</option>@foreach($product->processingOptions->where('is_active',true) as $option)<option value="{{ $option->id }}">{{ $option->name }} · {{ $option->minimum_business_days }}–{{ $option->maximum_business_days }} business days</option>@endforeach</select>@error('processingOptionId')<em role="alert">{{ $message }}</em>@enderror</label>
                </div>
            @elseif($step === 2)
                <div class="va-title"><span>Step 2 of 8</span><h1>Traveler details</h1><p>Enter names exactly as they appear on each passport.</p></div>
                @foreach($application->travelers as $traveler)<section class="va-person" wire:key="traveler-details-{{ $traveler->id }}"><h2>{{ $this->travelerLabel($traveler) }}</h2><div class="va-grid va-grid--3">
                    <label @class(['is-invalid' => $errors->has("travelers.{$traveler->id}.applicant_type")])><span>{{ $traveler->traveler_type === 'adult' ? 'Application profile' : 'Parent type' }} *</span><select wire:model.live="travelers.{{ $traveler->id }}.applicant_type" aria-invalid="{{ $errors->has("travelers.{$traveler->id}.applicant_type") ? 'true' : 'false' }}"><option value="">Select</option>@if($traveler->traveler_type === 'adult')<option value="individual">Individual</option><option value="company">Company-sponsored</option>@else<option value="minor_nigerian">Minor with Nigerian parent</option><option value="minor_foreign">Minor with foreign parent</option>@endif</select>@error("travelers.{$traveler->id}.applicant_type")<em role="alert">{{ $message }}</em>@enderror</label>
                    <label @class(['is-invalid' => $errors->has("travelers.{$traveler->id}.first_name")])><span>First name *</span><input wire:model.live.debounce.500ms="travelers.{{ $traveler->id }}.first_name" autocomplete="given-name" aria-invalid="{{ $errors->has("travelers.{$traveler->id}.first_name") ? 'true' : 'false' }}">@error("travelers.{$traveler->id}.first_name")<em role="alert">{{ $message }}</em>@enderror</label>
                    <label><span>Middle name</span><input wire:model.live.debounce.700ms="travelers.{{ $traveler->id }}.middle_name"></label>
                    @foreach(['last_name' => 'Last name', 'place_of_birth' => 'Place of birth', 'phone' => 'Phone'] as $field => $label)
                        <label @class(['is-invalid' => $errors->has("travelers.{$traveler->id}.$field")])><span>{{ $label }} *</span><input wire:model.live.debounce.500ms="travelers.{{ $traveler->id }}.{{ $field }}" @if($field==='last_name') autocomplete="family-name" @elseif($field==='phone') autocomplete="tel" inputmode="tel" @endif aria-invalid="{{ $errors->has("travelers.{$traveler->id}.$field") ? 'true' : 'false' }}">@error("travelers.{$traveler->id}.$field")<em role="alert">{{ $message }}</em>@enderror</label>
                    @endforeach
                    <label @class(['is-invalid' => $errors->has("travelers.{$traveler->id}.sex")])><span>Sex *</span><select wire:model.live="travelers.{{ $traveler->id }}.sex" aria-invalid="{{ $errors->has("travelers.{$traveler->id}.sex") ? 'true' : 'false' }}"><option value="">Select</option><option value="male">Male</option><option value="female">Female</option></select>@error("travelers.{$traveler->id}.sex")<em role="alert">{{ $message }}</em>@enderror</label>
                    <label @class(['is-invalid' => $errors->has("travelers.{$traveler->id}.date_of_birth")])><span>Date of birth *</span><input type="date" max="{{ now()->subDay()->toDateString() }}" wire:model.live="travelers.{{ $traveler->id }}.date_of_birth" aria-invalid="{{ $errors->has("travelers.{$traveler->id}.date_of_birth") ? 'true' : 'false' }}">@error("travelers.{$traveler->id}.date_of_birth")<em role="alert">{{ $message }}</em>@enderror</label>
                    <label @class(['is-invalid' => $errors->has("travelers.{$traveler->id}.nationality_country_id")])><span>Nationality *</span><select wire:model.live="travelers.{{ $traveler->id }}.nationality_country_id" aria-invalid="{{ $errors->has("travelers.{$traveler->id}.nationality_country_id") ? 'true' : 'false' }}"><option value="">Select nationality</option>@foreach($countries as $country)<option value="{{ $country->id }}">{{ $country->name }}</option>@endforeach</select>@error("travelers.{$traveler->id}.nationality_country_id")<em role="alert">{{ $message }}</em>@enderror</label>
                    <label @class(['is-invalid' => $errors->has("travelers.{$traveler->id}.email")])><span>Email</span><input type="email" wire:model.live.debounce.500ms="travelers.{{ $traveler->id }}.email" aria-invalid="{{ $errors->has("travelers.{$traveler->id}.email") ? 'true' : 'false' }}">@error("travelers.{$traveler->id}.email")<em role="alert">{{ $message }}</em>@enderror</label>
                    <label @class(['va-span', 'is-invalid' => $errors->has("travelers.{$traveler->id}.home_address")])><span>Home address *</span><textarea wire:model.live.debounce.500ms="travelers.{{ $traveler->id }}.home_address" aria-invalid="{{ $errors->has("travelers.{$traveler->id}.home_address") ? 'true' : 'false' }}"></textarea>@error("travelers.{$traveler->id}.home_address")<em role="alert">{{ $message }}</em>@enderror</label>
                </div></section>@endforeach
            @elseif($step === 3)
                <div class="va-title"><span>Step 3 of 8</span><h1>Passport information</h1><p>Use a passport valid beyond your planned departure date.</p></div>
                @foreach($application->travelers as $traveler)<section class="va-person" wire:key="traveler-passport-{{ $traveler->id }}"><h2>{{ $this->travelerLabel($traveler) }}</h2><div class="va-grid va-grid--2">
                    <label @class(['is-invalid' => $errors->has("travelers.{$traveler->id}.passport_number")])><span>Passport number *</span><input wire:model.live.debounce.500ms="travelers.{{ $traveler->id }}.passport_number" autocomplete="off" aria-invalid="{{ $errors->has("travelers.{$traveler->id}.passport_number") ? 'true' : 'false' }}">@error("travelers.{$traveler->id}.passport_number")<em role="alert">{{ $message }}</em>@enderror</label>
                    <label @class(['is-invalid' => $errors->has("travelers.{$traveler->id}.passport_type")])><span>Passport type *</span><select wire:model.live="travelers.{{ $traveler->id }}.passport_type" aria-invalid="{{ $errors->has("travelers.{$traveler->id}.passport_type") ? 'true' : 'false' }}"><option value="">Select</option><option value="ordinary">Ordinary</option><option value="official">Official</option><option value="diplomatic">Diplomatic</option></select>@error("travelers.{$traveler->id}.passport_type")<em role="alert">{{ $message }}</em>@enderror</label>
                    <label @class(['is-invalid' => $errors->has("travelers.{$traveler->id}.passport_issued_at")])><span>Issue date *</span><input type="date" max="{{ now()->toDateString() }}" wire:model.live="travelers.{{ $traveler->id }}.passport_issued_at" aria-invalid="{{ $errors->has("travelers.{$traveler->id}.passport_issued_at") ? 'true' : 'false' }}">@error("travelers.{$traveler->id}.passport_issued_at")<em role="alert">{{ $message }}</em>@enderror</label>
                    <label @class(['is-invalid' => $errors->has("travelers.{$traveler->id}.passport_expires_at")])><span>Expiry date *</span><input type="date" min="{{ $application->departure_date->copy()->addDay()->toDateString() }}" wire:model.live="travelers.{{ $traveler->id }}.passport_expires_at" aria-invalid="{{ $errors->has("travelers.{$traveler->id}.passport_expires_at") ? 'true' : 'false' }}">@error("travelers.{$traveler->id}.passport_expires_at")<em role="alert">{{ $message }}</em>@enderror</label>
                    <label @class(['is-invalid' => $errors->has("travelers.{$traveler->id}.passport_issuing_country_id")])><span>Issuing country *</span><select wire:model.live="travelers.{{ $traveler->id }}.passport_issuing_country_id" aria-invalid="{{ $errors->has("travelers.{$traveler->id}.passport_issuing_country_id") ? 'true' : 'false' }}"><option value="">Select country</option>@foreach($countries as $country)<option value="{{ $country->id }}">{{ $country->name }}</option>@endforeach</select>@error("travelers.{$traveler->id}.passport_issuing_country_id")<em role="alert">{{ $message }}</em>@enderror</label>
                </div></section>@endforeach
            @elseif($step === 4)
                <div class="va-title"><span>Step 4 of 8</span><h1>Additional questions</h1><p>Questions are configured for this visa product.</p></div>
                @forelse($product->questions->where('is_active',true) as $question)
                    @php $targets=$question->scope==='traveler'?$application->travelers:collect([null]); @endphp
                    @foreach($targets as $traveler)@php $key=$question->id.'_'.($traveler?->id?:'app'); @endphp<label @class(['va-question', 'is-invalid' => $errors->has("answers.$key")]) wire:key="question-{{ $question->id }}-{{ $traveler?->id ?: 'app' }}"><span>{{ $question->label }} @if($question->is_required)*@endif @if($traveler)<small>· {{ $this->travelerLabel($traveler) }}</small>@endif</span>
                        @if($question->input_type==='textarea')<textarea wire:model.live.debounce.700ms="answers.{{ $key }}"></textarea>
                        @elseif($question->input_type==='select')<select wire:model.live="answers.{{ $key }}"><option value="">Select</option>@foreach(($question->options??[]) as $option)<option value="{{ is_array($option)?($option['value']??$option['label']):$option }}">{{ is_array($option)?$option['label']:$option }}</option>@endforeach</select>
                        @elseif($question->input_type==='checkbox')<input type="checkbox" value="1" wire:model.live="answers.{{ $key }}">
                        @else<input type="{{ in_array($question->input_type,['date','email','number'])?$question->input_type:'text' }}" wire:model.live.debounce.700ms="answers.{{ $key }}">@endif
                        <small>{{ $question->help_text }}</small>@error("answers.$key")<em role="alert">{{ $message }}</em>@enderror</label>@endforeach
                @empty<div class="va-empty"><x-ui.icon name="check-circle" :size="48" /><h2>No additional questions</h2><p>This product does not require any extra answers.</p></div>@endforelse
            @elseif($step === 6)
                <div class="va-title"><span>Step 6 of 8</span><h1>Upload documents</h1><p>This includes visa documents and documents required by the TravelWheel services you selected.</p></div>
                <div class="va-uploads">@forelse($this->documentSlots() as $slot)@php $stored=$application->documents->first(fn($doc)=>$doc->visa_requirement_id==$slot['requirement_id'] && $doc->visa_traveler_id==$slot['traveler_id']); @endphp
                    <label @class(['va-upload', 'is-invalid' => $errors->has('uploads.'.$slot['key'])]) wire:key="upload-{{ $slot['key'] }}" x-data="{ fileName: '' }"><i class="fa-solid fa-upload va-upload__icon" aria-hidden="true"></i><span class="va-upload__copy"><strong>{{ $slot['label'] }}</strong><small>{{ $slot['required']?'Required':'Upload if applicable' }}{{ $slot['guidance']?' · '.$slot['guidance']:'' }}</small>@if($stored)<b>Uploaded: {{ $stored->original_name }}</b>@endif</span><span class="va-upload__action"><i class="fa-solid fa-folder-open" aria-hidden="true"></i><span x-text="fileName || 'Choose file'">Choose file</span></span><input class="va-upload__input" type="file" wire:model="uploads.{{ $slot['key'] }}" accept=".pdf,.jpg,.jpeg,.png" @change="fileName = $event.target.files[0]?.name || ''" aria-invalid="{{ $errors->has('uploads.'.$slot['key']) ? 'true' : 'false' }}"><em wire:loading wire:target="uploads.{{ $slot['key'] }}">Preparing file…</em>@error('uploads.'.$slot['key'])<em role="alert">{{ $message }}</em>@enderror</label>
                @empty<div class="va-empty"><h2>No document uploads configured</h2><p>The visa team will contact you if anything is needed.</p></div>@endforelse</div>
            @elseif($step === 5)
                <div class="va-title"><span>Step 5 of 8</span><h1>TravelWheel services</h1><p>Choose services first so we can show any documents needed for them on the next step.</p></div>
                @forelse($product->optionalServices->where('is_active',true) as $service)@php $serviceIcon=$service->service_type==='flight'?'plane':($service->service_type==='hotel'?'hotel':'shield'); @endphp<label class="va-service"><input type="checkbox" wire:model.live="serviceSelections.{{ $service->id }}"><x-ui.icon :name="$serviceIcon" :size="22" /><span><strong>{{ $service->name }}</strong><small>{{ $service->description }}</small></span>@if($service->amount)<b>{{ $service->currency }} {{ number_format($service->amount,2) }}</b>@endif</label>@empty<div class="va-empty"><h2>No optional services</h2><p>You can continue without adding anything.</p></div>@endforelse
            @elseif($step === 7)
                <div class="va-title"><span>Step 7 of 8</span><h1>Review and declare</h1><p>Check the summary before proceeding to quotation and payment.</p></div>
                <div class="va-review"><section><h2>Trip</h2><p>{{ data_get($application->search_snapshot,'nationality_name') }} → {{ data_get($application->search_snapshot,'destination_name') }}</p><small>{{ $application->arrival_date->format('d M Y') }} – {{ $application->departure_date->format('d M Y') }}</small></section><section><h2>Travelers</h2>@foreach($application->travelers as $traveler)<p>{{ $this->travelerLabel($traveler) }}: {{ data_get($travelers,$traveler->id.'.first_name') }} {{ data_get($travelers,$traveler->id.'.last_name') }}</p>@endforeach</section><section><h2>Documents</h2><p>{{ $application->documents->count() }} uploaded</p></section></div>
                <label @class(['va-declaration', 'is-invalid' => $errors->has('declarationAccepted')])><input type="checkbox" wire:model.live="declarationAccepted" aria-invalid="{{ $errors->has('declarationAccepted') ? 'true' : 'false' }}"><span>I confirm that the information supplied is accurate and belongs to the named travelers. I understand that TravelWheel cannot guarantee visa issuance.</span></label>@error('declarationAccepted')<em class="va-error" role="alert">{{ $message }}</em>@enderror
            @else
                @php $activeQuote=$application->quotes()->with('items')->where('status','active')->where('expires_at','>',now())->latest()->first(); @endphp
                <div class="va-title"><span>Step 8 of 8</span><h1>Quotation and payment</h1><p>Every amount below is recalculated on the server from the current product configuration.</p></div>
                @if(!$activeQuote)
                    <div class="va-ready"><x-ui.icon name="check-circle" :size="48" /><h2>Application details complete</h2><p>Generate an immutable quotation before continuing to SeerBit.</p><form method="POST" action="{{ route('visa.quotes.create',$application) }}">@csrf<button class="va-primary" type="submit">Generate secure quote <x-ui.icon name="arrow-right" :size="17" /></button></form></div>
                @else
                    <div class="va-quote"><div class="va-quote__head"><div><small>Quote {{ $activeQuote->reference }}</small><h2>Amount payable now</h2></div><strong>NGN {{ number_format($activeQuote->payable_total,2) }}</strong></div><div class="va-quote__items">@foreach($activeQuote->items as $item)<div><span>{{ $item->name }} <small>{{ rtrim(rtrim(number_format($item->quantity,2),'0'),'.') }} × {{ $item->source_currency }} {{ number_format($item->source_unit_amount,2) }}</small></span><strong>{{ $item->pay_online ? 'NGN '.number_format($item->checkout_total,2) : 'Paid to authority' }}</strong></div>@endforeach</div><footer><span>Expires {{ $activeQuote->expires_at->diffForHumans() }}</span><form method="POST" action="{{ route('visa.payments.initialize',$activeQuote) }}">@csrf<button class="va-primary" type="submit">Pay securely with SeerBit <x-ui.icon name="lock" :size="17" /></button></form></footer></div>
                @endif
            @endif

            <footer class="va-actions">@if($step>1 && $application->status !== 'awaiting_payment')<button type="button" class="va-secondary" wire:click="previous">Back</button>@else<span></span>@endif @if($step<8)<button type="button" class="va-primary" wire:click="next" wire:loading.attr="disabled">Save and continue <x-ui.icon name="arrow-right" :size="17" /></button>@endif</footer>
        </main>

        <aside class="va-aside"><div><small>Your visa</small><h2>{{ $product->name }}</h2><p>{{ $product->family->value === 'voa' ? 'Visa on arrival' : 'Standard visa' }} · {{ ucfirst($product->entry_type) }} entry</p></div><dl><div><dt>Destination</dt><dd>{{ data_get($application->search_snapshot,'destination_name') }}</dd></div><div><dt>Validity</dt><dd>{{ $product->validity_days ? $product->validity_days.' days' : 'Confirmed after review' }}</dd></div><div><dt>Draft expires</dt><dd>{{ $application->expires_at->format('d M Y') }}</dd></div></dl><p><x-ui.icon name="lock" :size="17" /> Passport details and uploads are encrypted or held in private storage.</p></aside>
    </div>
</div>
