<option value="">-- Select Country --</option>
<option value="114">Afghanistan</option>
<option value="116">Albania</option>
<option value="150">Algeria</option>
<option value="113">Andorra</option>
<option value="118">Angola</option>
<option value="115">Anguilla</option>
<option value="175">Antigua</option>
<option value="119">Argentina</option>
<option value="117">Armenia</option>
<option value="120">Australia</option>
<option value="2">Austria</option>
<option value="121">Azerbaijan</option>
<option value="132">Bahamas</option>
<option value="126">Bahrain</option>
<option value="123">Bangladesh</option>
<option value="122">Barbados</option>
<option value="135">Belarus</option>
<option value="3">Belgium</option>
<option value="136">Belize</option>
<option value="128">Benin</option>
<option value="129">Bermuda</option>
<option value="133">Bhutan</option>
<option value="176">Bolivia</option>
<option value="177">BOSNIA</option>
<option value="134">Botswana</option>
<option value="131">Brazil</option>
<option value="130">Brunei Darussalam</option>
<option value="125">Bulgaria</option>
<option value="124">Burkina Faso</option>
<option value="127">Burundi</option>
<option value="170">Cambodia</option>
<option value="140">Cameroon</option>
<option value="4">Canada</option>
<option value="145">Cape Verde</option>
<option value="172">Cayman Islands</option>
<option value="137">Central African Republic</option>
<option value="174">Chad</option>
<option value="139">Chile</option>
<option value="141">China</option>
<option value="142">Colombia</option>
<option value="171">Comoros</option>
<option value="138">Congo</option>
<option value="143">Costa Rica</option>
<option value="168">Croatia</option>
<option value="144">Cuba</option>
<option value="146">Cyprus</option>
<option value="6">Czech Republic</option>
<option value="178">Democratic Republic of the Congo</option>
<option value="8">Denmark</option>
<option value="147">Djibouti</option>
<option value="148">Dominica</option>
<option value="149">Dominican Republic</option>
<option value="151">Ecuador</option>
<option value="152">Egypt</option>
<option value="173">El Salvador</option>
<option value="164">Equatorial Guinea</option>
<option value="153">Eritrea</option>
<option value="9">Estonia</option>
<option value="154">Ethiopia</option>
<option value="155">Fiji</option>
<option value="11">Finland</option>
<option value="12">France</option>
<option value="159">French Guiana</option>
<option value="156">Gabon</option>
<option value="161">Gambia</option>
<option value="158">Georgia</option>
<option value="7">Germany</option>
<option value="160">Ghana</option>
<option value="13">Greece</option>
<option value="157">Grenada</option>
<option value="163">Guadeloupe</option>
<option value="165">Guatemala</option>
<option value="162">Guinea</option>
<option value="166">Guinea-Bissau</option>
<option value="167">Guyana</option>
<option value="169">Haiti</option>
<option value="14">Honduras</option>
<option value="15">Hungary</option>
<option value="19">Iceland</option>
<option value="17">India</option>
<option value="16">Indonesia</option>
<option value="180">Iran</option>
<option value="18">Iraq</option>
<option value="200">Ireland</option>
<option value="181">Israel</option>
<option value="20">Italy</option>
<option value="182">Ivory Coast</option>
<option value="21">Jamaica</option>
<option value="23">Japan</option>
<option value="22">Jordan</option>
<option value="27">Kazakhstan</option>
<option value="24">Kenya</option>
<option value="183">Korea, Democratic Republic of (North Korea)</option>
<option value="185">KOSOVO</option>
<option value="26">Kuwait</option>
<option value="186">Kyrgyz Republic (Kyrgyzstan)</option>
<option value="187">Laos</option>
<option value="36">Latvia</option>
<option value="28">Lebanon</option>
<option value="33">Lesotho</option>
<option value="32">Liberia</option>
<option value="37">Libya</option>
<option value="30">Liechtenstein</option>
<option value="34">Lithuania</option>
<option value="35">Luxembourg</option>
<option value="42">Madagascar</option>
<option value="51">Malawi</option>
<option value="53">Malaysia</option>
<option value="50">Maldives</option>
<option value="43">Mali</option>
<option value="48">Malta</option>
<option value="45">Martinique</option>
<option value="46">Mauritania</option>
<option value="49">Mauritius</option>
<option value="109">Mayotte</option>
<option value="52">Mexico</option>
<option value="39">Monaco</option>
<option value="44">Mongolia</option>
<option value="41">Montenegro</option>
<option value="47">Montserrat</option>
<option value="38">Morocco</option>
<option value="54">Mozambique</option>
<option value="188">Myanmar/Burma</option>
<option value="55">Namibia</option>
<option value="61">Nepal</option>
<option value="59">Netherlands</option>
<option value="62">New Zealand</option>
<option value="58">Nicaragua</option>
<option value="56">Niger</option>
<option value="60">Norway</option>
<option value="63">Oman</option>
<option value="189">Pacific Islands</option>
<option value="68">Pakistan</option>
<option value="64">Panama</option>
<option value="66">Papua New Guinea</option>
<option value="72">Paraguay</option>
<option value="65">Peru</option>
<option value="67">Philippines</option>
<option value="69">Poland</option>
<option value="71">Portugal</option>
<option value="70">Puerto Rico</option>
<option value="73">Qatar</option>
<option value="190">Republic of Macedonia</option>
<option value="40">Republic of Moldova</option>
<option value="191">Reunion</option>
<option value="74">Romania</option>
<option value="76">Russian Federation</option>
<option value="77">Rwanda</option>
<option value="25">Saint Kitts &amp; Nevis</option>
<option value="29">Saint Lucia</option>
<option value="192">Saint Vincent's &amp; Grenadines</option>
<option value="107">Samoa</option>
<option value="91">Sao Tome &amp; Principe</option>
<option value="78">Saudi Arabia</option>
<option value="87">Senegal</option>
<option value="75">Serbia</option>
<option value="80">Seychelles</option>
<option value="86">Sierra Leone</option>
<option value="83">Singapore</option>
<option value="201">Sint Maarten (Dutch part)</option>
<option value="193">Slovak Republic (Slovakia)</option>
<option value="85">SLOVAKIA</option>
<option value="84">Slovenia</option>
<option value="79">Solomon Islands</option>
<option value="88">Somalia</option>
<option value="110">South Africa</option>
<option value="184">South Korea</option>
<option value="90">South Sudan</option>
<option value="10">Spain</option>
<option value="31">Sri Lanka</option>
<option value="81">Sudan</option>
<option value="89">Suriname</option>
<option value="92">Swaziland</option>
<option value="82">Sweden</option>
<option value="5">Switzerland</option>
<option value="194">Syria</option>
<option value="202">Taiwan</option>
<option value="95">Tajikistan</option>
<option value="195">Tanzania</option>
<option value="94">Thailand</option>
<option value="196">Timor Leste</option>
<option value="93">Togo</option>
<option value="197">Trinidad &amp; Tobago</option>
<option value="97">Tunisia</option>
<option value="98">Turkey</option>
<option value="96">Turkmenistan</option>
<option value="198">Turks &amp; Caicos Islands</option>
<option value="100">Uganda</option>
<option value="99">Ukraine</option>
<option value="1">United Arab Emirates</option>
<option value="179">United Kingdom</option>
<option value="199">United States of America</option>
<option value="101">Uruguay</option>
<option value="102">Uzbekistan</option>
<option value="103">Venezuela</option>
<option value="106">Vietnam</option>
<option value="104">VIRGIN ISLANDS (BRITISH)</option>
<option value="105">VIRGIN ISLANDS (US)</option>
<option value="108">Yemen</option>
<option value="111">Zambia</option>
<option value="112">Zimbabwe</option>
