<option value="">-- Select state --</option>
<option value="1">Abia State</option>
<option value="2">Adamawa State</option>
<option value="3">Akwa Ibom State</option>
<option value="4">Anambra State</option>
<option value="5">Bauchi State</option>
<option value="6">Bayelsa State</option>
<option value="7">Benue State</option>
<option value="8">Borno State</option>
<option value="9">Cross River State</option>
<option value="10">Delta State</option>
<option value="11">Ebonyi State</option>
<option value="12">Edo State</option>
<option value="13">Ekiti State</option>
<option value="14">Enugu State</option>
<option value="15">FCT</option>
<option value="16">Gombe State</option>
<option value="17">Imo State</option>
<option value="18">Jigawa State</option>
<option value="19">Kaduna State</option>
<option value="20">Kano State</option>
<option value="21">Katsina State</option>
<option value="22">Kebbi State</option>
<option value="23">Kogi State</option>
<option value="24">Kwara State</option>
<option value="25">Lagos State</option>
<option value="26">Nasarawa State</option>
<option value="27">Niger State</option>
<option value="28">Ogun State</option>
<option value="29">Ondo State</option>
<option value="30">Osun State</option>
<option value="31">Oyo State</option>
<option value="32">Plateau State</option>
<option value="33">Rivers State</option>
<option value="34">Sokoto State</option>
<option value="35">Taraba State</option>
<option value="36">Yobe State</option>
<option value="37">Zamfara State</option>
