<option value="">-- Select Title --</option>
<option value="1">Alhaja</option>
<option value="2">Alhaji</option>
<option value="3">Amb.</option>
<option value="4">Barr.</option>
<option value="5">Bishop</option>
<option value="6">Captain</option>
<option value="7">Chief</option>
<option value="8">Chief (Mrs.)</option>
<option value="9">Deacon</option>
<option value="10">Deacon &amp; Deaconess</option>
<option value="11">Deaconess</option>
<option value="12">Dr.</option>
<option value="13">Dr. (Mrs.)</option>
<option value="14">Engr.</option>
<option value="15">H.R.H</option>
<option value="16">LEUT.</option>
<option value="17">LUET. COMMANDER</option>
<option value="18">Miss.</option>
<option value="19">Most Rev. Fr.</option>
<option value="20">Mr.</option>
<option value="21">Mr. &amp; Mrs.</option>
<option value="22">Mrs.</option>
<option value="23">Very Rev. Fr.</option>
<option value="24">Pastor</option>
<option value="25">Prince</option>
<option value="26">Prof.</option>
<option value="27">Rev.</option>
<option value="28">Rev. &amp; Mrs</option>
<option value="29">Rev. Fr.</option>
<option value="30">Sir</option>
<option value="31">Ven</option>
